"""add total_units to position

Revision ID: 7c8b206f7b37
Revises: dc7951d9924f
Create Date: 2026-05-23 12:42:49.364646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8b206f7b37'
down_revision: Union[str, Sequence[str], None] = 'dc7951d9924f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('total_units', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'total_units')
    # ### end Alembic commands ###
