"""initial: etf, strategy_params, ohlc, position, trade

Revision ID: dc7951d9924f
Revises: 
Create Date: 2026-05-22 18:58:23.345176

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7951d9924f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('COMMODITIES', 'SECTORAL', 'INDIAN_INDEX', 'INTERNATIONAL', name='etfcategory'), nullable=False),
    sa.Column('amc', sa.String(length=100), nullable=False),
    sa.Column('underlying_exposure', sa.Text(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('ohlc',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('ema21', sa.Float(), nullable=True),
    sa.Column('ema60', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_ohlc_date'), 'ohlc', ['date'], unique=False)
    op.create_index(op.f('ix_ohlc_symbol'), 'ohlc', ['symbol'], unique=False)
    op.create_table('strategy_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('param_name', sa.String(length=100), nullable=False),
    sa.Column('param_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_name')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etf_symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FLAT', name='positionstatus'), nullable=False),
    sa.Column('total_capital_deployed', sa.Float(), nullable=False),
    sa.Column('tranches_used', sa.Integer(), nullable=False),
    sa.Column('last_buy_price', sa.Float(), nullable=True),
    sa.Column('weighted_avg_cost', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('trend_regime', sa.Enum('STRONG', 'NEUTRAL', 'WEAK', name='trendregime'), nullable=True),
    sa.Column('entered_at', sa.Date(), nullable=True),
    sa.Column('exited_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['etf_symbol'], ['etf.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_symbol')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('ENTRY', 'ADDON', 'EXIT_PROFIT', 'EXIT_TIME', name='tradeaction'), nullable=False),
    sa.Column('tranche_number', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('order_status', sa.Enum('PENDING', 'FILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('order_placed_at', sa.DateTime(), nullable=False),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_position_id'), 'trade', ['position_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_position_id'), table_name='trade')
    op.drop_table('trade')
    op.drop_table('position')
    op.drop_table('strategy_params')
    op.drop_index(op.f('ix_ohlc_symbol'), table_name='ohlc')
    op.drop_index(op.f('ix_ohlc_date'), table_name='ohlc')
    op.drop_table('ohlc')
    op.drop_table('etf')
    # ### end Alembic commands ###
